<%@ include file="/common/taglibs.jsp"%>
<form:form id="addMember" method="post" data-remote="true" action="bpm/form/saveFormAutoGenerationId" accept-charset="UTF-8" onSubmit="closeSelectDialog('formAutoGenerationId'); _execute('target','');" >
	<div id="idGeneration" class="padding20" style="width:300px;">
		<div class="width-per-100 height60">
			<div id="autoIdLabel" class="floatLeft width-per-25 "><fmt:message key="form.autoId"/></div>
			<div class="width-per-70 floatLeft">
				<input type="text" name="autoId" id="autoId" class="large"/>
				<span class="style16" id="helpText"></span>
			</div>
		</div>
		<!-- <div id="prefix_generation" class="width-per-100 height60">
			<div id="prefixLabel" class="floatLeft width-per-25 ">Prefix Code</div>
			<div class="width-per-70 floatLeft">
				<input type="text" name="prefix" id="prefix" class="large" onblur="generateFormAutoId()" required="required" maxlength="5"/>
				<span class="style16">(Max characters limit is 5.)</span>
			</div>
		</div>
		<div id="title_generation" class="width-per-100 height45">
			<div id="titleLabel" class="floatLeft width-per-25">Title</div>
			<div class="width-per-70 floatLeft"><select name="title" id="title" class="large" onChange="generateFormAutoId()" required="required"></select></div>
		</div>
		<div id="year_generation" class="width-per-100 height45">
			<div id="yearLabel" class="floatLeft width-per-25">Year</div>
			<div class="width-per-70 floatLeft">
				<select name="year" id="year" class="large" onChange="generateFormAutoId();" onblur="generateFormAutoId();"><option value=""></option><option value="yy">yy</option><option value="yyyy">yyyy</option></select>
			</div>
		</div>
		<div id="month_generation" class="width-per-100 height45">
			<div id="monthLabel" class="floatLeft width-per-25">Month</div>
			<div class="width-per-70 floatLeft">
				<select name="month" id="month" class="large" onChange="generateFormAutoId()" onblur="generateFormAutoId()"><option value=""></option><option value="MM">MM</option></select>
			</div>
		</div>
		<div id="day_generation" class="width-per-100 height45">
			<div id="dayLabel" class="floatLeft width-per-25">Day</div>
			<div class="width-per-70 floatLeft">
				<select name="day" id="day" class="large" onChange="generateFormAutoId()" onblur="generateFormAutoId()"><option value=""></option><option value="dd">dd</option></select>
			</div>
		</div>
		<div id="seperator_generation" class="width-per-100 height45">
			<div class="floatLeft width-per-25">Seperator</div>
			<div class="width-per-70 floatLeft"><select name="seperator" id="seperator" class="large" onChange="generateFormAutoId()" onblur="generateFormAutoId()"><option value="/">/</option><option value="|">|</option><option value="-">-</option></select></div>
		</div>
		<div id="formAutoId" class="width-per-100 height45">
            <div class="width-per-100 floatLeft" colspan="2"><input type="text" name="autoIdFormat" id="autoIdFormat" class="large" readonly="readonly"/></div>
        </div> -->
		<div class="width-per-95" align="center">
			 <input id="saveButton" type="submit" value="Save" class="btn btn-primary normalButton mar-L10 padding0 line-height0"/>
			 <input type="button" value="Cancel" class="btn btn-small clearButton mar-L10 pad-B3 height25" onclick="closeSelectDialog('formAutoGenerationId');"/>
		</div>
	</div>
	<!--<div id="createdAutoId"class="padding20" style="width:400px;display:none;">
		<div id="generated_id" class="width-per-100 height45">
			<div class="floatLeft width-per-30 ">Id Expression </div>
			<div class="width-per-70 floatLeft" ><input type="text" name="generatedId" id="generatedId" class="large" readonly="readonly"/></div>
		</div>
		<div id="sample_id" class="width-per-100 height45">
			<div class="floatLeft width-per-30 ">Sample Id </div>
			<div class="width-per-70 floatLeft" ><input type="text" name="sampleAutoId" id="sampleAutoId" class="large" readonly="readonly"/></div>
		</div>
	</div> -->
	<input type="hidden" name="formId" id="formId" value="${formId}">
	<input type="hidden" name="autoGeneratedId" id="autoGeneratedId" value="${autoGeneratedId}">
	<%-- <input type="hidden" name="sampleAutoGeneratedId" id="sampleAutoGeneratedId" value="${sampleAutoGeneratedId}"> --%>
</form:form>
<script>
/* $(document).ready(function(){ 
	var autoGeneratedId = document.getElementById("autoGeneratedId").value;
	if(autoGeneratedId != null && autoGeneratedId != 'null' && autoGeneratedId != ""){
		var sampleAutoGeneratedId = document.getElementById("sampleAutoGeneratedId").value;
		document.getElementById("generatedId").value = autoGeneratedId;
		document.getElementById("sampleAutoId").value = sampleAutoGeneratedId;
		
		document.getElementById("createdAutoId").style.display = 'block';
		document.getElementById("idGeneration").style.display = 'none';
	}else{
		document.getElementById("idGeneration").style.display = 'block';
		document.getElementById("createdAutoId").style.display = 'none';
		document.getElementById("autoId").focus();
		var selectObj=document.getElementById("title");
		var formId = document.getElementById("formId").value;
 		$.ajax({	
			type: 'GET',
			async: false,
			url : '/bpm/form/getAllFormFields',
			data: 'formId=' + formId,
			success : function(response) {
				for(var i=0;i<response.forms.length;i++){
					if(i==0){
						var emptySelectOption = document.createElement("OPTION");
						emptySelectOption.text = '';
						emptySelectOption.value = '';
						selectObj.options.add(emptySelectOption);
					}
					var selectOption = document.createElement("OPTION");
					selectOption.text = response.forms[i].name;
					selectOption.value = response.forms[i].name;
					selectObj.options.add(selectOption);
				}
			}
		}); 
	}
}); */

$(document).ready(function(){ 
	var autoGeneratedId = document.getElementById("autoGeneratedId").value;
	if(autoGeneratedId != null && autoGeneratedId != 'null' && autoGeneratedId != ""){
		document.getElementById("saveButton").value = 'Update';
		document.getElementById("autoId").value = autoGeneratedId;
		document.getElementById("helpText").innerHTML = '';
	}else{
		document.getElementById("helpText").innerHTML = 'ETBPM|{Field}|{Year}|{Month}|{Day}';
		document.getElementById("saveButton").value = 'Save';
		document.getElementById("autoId").focus();
	}
}); 
</script>
